{
 "title": "Test-Cluster-EinsteinDB-Trouble-Shooting",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "db",
    "query": "label_values(einsteindb_engine_block_cache_size_bytes, db)"
   },
   {
    "name": "command",
    "label": "command",
    "query": "label_values(einsteindb_causetStorage_command_total, type)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(einsteindb_engine_size_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hot Read",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "description": "总 CPU 使用率",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "客户端发来的常见请求的 QPS。如果同一类请求在多个机器上分布显著不平均，那么需要考虑热点的问题",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"interlock|kv_get|kv_batch_get|kv_prewrite|kv_commit\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "CausetStorage ReadPool CPU",
     "type": "graph",
     "description": "点查会走 CausetStorage ReadPool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_norm.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - normal"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_high.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - high"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_low.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - low"
      }
     ]
    },
    {
     "title": "Interlock CPU",
     "type": "graph",
     "description": "非点查的 SQL 走 Interlock Pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_normal.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - normal"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_high.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - high"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_low.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - low"
      }
     ]
    },
    {
     "title": "gRPC poll CPU",
     "type": "graph",
     "description": "gRPC CPU 使用率，如果打满，需要调 EinsteinDB 的 grpc-concurrency 参数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"grpc.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IO utilization",
     "type": "graph",
     "description": "I/O util 反应磁盘的繁忙程度。接近 100% 意味着磁盘很忙，虽然未必达到了贷款瓶颈，但是延迟可能会受较大影响。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[1m])",
       "leglightlikeFormat": "{{instance}} - {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hot Write",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_duration_seconds_count{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (instance,type)",
       "leglightlikeFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "IO utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[1m])",
       "leglightlikeFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "gRPC poll CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"grpc.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "VioletaBft store CPU",
     "type": "graph",
     "description": "VioletaBftstore 线程 CPU 使用率，这个线程池用来写 VioletaBft log。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"violetabftstore_.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Async apply CPU",
     "type": "graph",
     "description": "Apply 线程 CPU，这个线程池用来将写入应用到 kv engine 中。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"apply_[0-9]+\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interlock_Semaphore Worker CPU",
     "type": "graph",
     "description": "Interlock_Semaphore worker 线程池的 CPU 使用率。事务会在 Interlock_Semaphore 中排队，这个线程池接近打满意味着 MVCC 的旧版本太多，事务处理过慢。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"sched_worker.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Leader Drop",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leader",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_violetabftstore_brane_count{instance=~\"$instance\", type=\"leader\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Applightlike log duration",
     "type": "graph",
     "description": "Applightlike log 时间。过长意味着 VioletaBftstore 线程太忙，有可能心跳处理不过来导致上面的 Leader 被切走。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999999, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": " 99.9999%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_sum{instance=~\"$instance\"}[1m])) / sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_count{instance=~\"$instance\"}[1m]))",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Propose 99.9999% wait duration",
     "type": "graph",
     "description": "Propose 如果在 VioletaBftstore 中等得太久，则说明 VioletaBftstore 线程很忙，或者被卡住了。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999999, sum(rate(einsteindb_violetabftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "VioletaBft Lmdb write duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "VioletaBft event 99.9999% handle duration",
     "type": "graph",
     "description": "VioletaBftstore 线程需要处理一些周期性任务。如果处理时间过长，则相当于 VioletaBftstore 线程被卡住了。",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999999, sum(rate(einsteindb_violetabftstore_event_duration_bucket{instance=~\"$instance\"}[1m])) by (le, instance, type))",
       "leglightlikeFormat": "{{instance}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel Full",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Channel full",
     "type": "graph",
     "description": "EinsteinDB 的 VioletaBftstore 会在处理不过来消息时发生 channel full，此时后续的消息会被丢弃掉，可能会导致 MilevaDB 重试或者掉 Leader。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_channel_full_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "VioletaBft Lmdb write stall duration",
     "type": "graph",
     "description": "Lmdb write stall 说明写入请求被 compaction 或者其他流量控制措施卡住了。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", db=\"violetabft\", type=\"write_stall_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", db=\"violetabft\", type=\"write_stall_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", db=\"violetabft\", type=\"write_stall_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", db=\"violetabft\", type=\"write_stall_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Applightlike log duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": " 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_sum{instance=~\"$instance\"}[1m])) / sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_count{instance=~\"$instance\"}[1m]))",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Applightlike log duration per server",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Commit log duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_sum{instance=~\"$instance\"}[1m])) / sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_count{instance=~\"$instance\"}[1m]))",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Commit log duration per server",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Is Busy",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server is busy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_interlock_semaphore_too_busy_total{instance=~\"$instance\"}[1m])) by (instance)",
       "leglightlikeFormat": "interlock_semaphore-{{instance}}"
      },
      {
       "expr": "sum(rate(einsteindb_channel_full_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "channelfull-{{instance}}-{{type}}"
      },
      {
       "expr": "sum(rate(einsteindb_interlock_request_error{instance=~\"$instance\", type='full'}[1m])) by (instance)",
       "leglightlikeFormat": "interlock-{{instance}}"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile99\"}) by (instance)",
       "leglightlikeFormat": "stall-{{instance}}"
      }
     ]
    },
    {
     "title": "Interlock_Semaphore plightlikeing commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_interlock_semaphore_contex_total{instance=~\"$instance\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Channel full",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_channel_full_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "Lmdb write stall duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_max\"}) by (db)",
       "leglightlikeFormat": "{{db}} max"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile99\"}) by (db)",
       "leglightlikeFormat": "{{db}} 99%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile95\"}) by (db)",
       "leglightlikeFormat": "{{db}} 95%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_average\"}) by (db)",
       "leglightlikeFormat": "{{db}} avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Read Too Slow",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% gRPC messge duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gRPC poll CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"grpc.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interlock CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_normal.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - normal"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_high.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - high"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_low.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - low"
      }
     ]
    },
    {
     "title": "CausetStorage ReadPool CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_norm.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - normal"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_high.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - high"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_low.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - low"
      }
     ]
    },
    {
     "title": "Interlock request duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(einsteindb_interlock_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-99.99%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_interlock_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-95%"
      },
      {
       "expr": " sum(rate(einsteindb_interlock_request_duration_seconds_sum{instance=~\"$instance\"}[1m])) by (req) / sum(rate(einsteindb_interlock_request_duration_seconds_count{instance=~\"$instance\"}[1m])) by (req)",
       "leglightlikeFormat": "{{req}}-avg"
      }
     ]
    },
    {
     "title": "Interlock wait duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(einsteindb_interlock_request_wait_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-99.99%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_request_wait_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_interlock_request_wait_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-95%"
      },
      {
       "expr": " sum(rate(einsteindb_interlock_request_wait_seconds_sum{instance=~\"$instance\"}[1m])) by (req) / sum(rate(einsteindb_interlock_request_wait_seconds_count{instance=~\"$instance\"}[1m])) by (req)",
       "leglightlikeFormat": "{{req}}-avg"
      }
     ]
    },
    {
     "title": "Interlock scan tuplespaceInstanton",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, avg(rate(einsteindb_interlock_scan_tuplespaceInstanton_bucket{instance=~\"$instance\"}[1m])) by (le, req))  ",
       "leglightlikeFormat": "{{req}}-99.99%"
      },
      {
       "expr": "histogram_quantile(0.99, avg(rate(einsteindb_interlock_scan_tuplespaceInstanton_bucket{instance=~\"$instance\"}[1m])) by (le, req))  ",
       "leglightlikeFormat": "{{req}}-99%"
      },
      {
       "expr": "histogram_quantile(0.95, avg(rate(einsteindb_interlock_scan_tuplespaceInstanton_bucket{instance=~\"$instance\"}[1m])) by (le, req))  ",
       "leglightlikeFormat": "{{req}}-95%"
      },
      {
       "expr": "histogram_quantile(0.90, avg(rate(einsteindb_interlock_scan_tuplespaceInstanton_bucket{instance=~\"$instance\"}[1m])) by (le, req))  ",
       "leglightlikeFormat": "{{req}}-90%"
      }
     ]
    },
    {
     "title": "95% Interlock wait duration by store",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_interlock_request_wait_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance,req))",
       "leglightlikeFormat": "{{instance}}-{{req}}"
      }
     ]
    },
    {
     "title": "Get snapshot duration",
     "type": "graph",
     "description": "读请求执行前，都需要拿一个 snapshot",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999999, sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_bucket{instance=~\"$instance\", type=\"snapshot\"}[1m])) by (le))",
       "leglightlikeFormat": "99.9999%"
      },
      {
       "expr": "sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_sum{instance=~\"$instance\", type=\"snapshot\"}[1m])) / sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_count{instance=~\"$instance\", type=\"snapshot\"}[1m]))",
       "leglightlikeFormat": "average"
      }
     ]
    },
    {
     "title": "Lmdb get duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_get_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"get_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "avg(einsteindb_engine_get_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"get_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "avg(einsteindb_engine_get_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"get_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "avg(einsteindb_engine_get_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"get_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Lmdb seek duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_seek_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"seek_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "avg(einsteindb_engine_seek_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"seek_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "avg(einsteindb_engine_seek_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"seek_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "avg(einsteindb_engine_seek_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"seek_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Disk Read Latency (ms)",
     "type": "graph",
     "description": "Disk seconds Read Latency.\n- Critical:\n  - Recommlightlikeed performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total[5m])/ rate(node_disk_reads_completed_total[5m])) > 0",
       "leglightlikeFormat": "{{instance}}: [{{ device }}]"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[5m]) + irate(node_disk_written_bytes_total[5m]) > 0",
       "leglightlikeFormat": "{{instance}}: [{{ device }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Too Slow",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% gRPC messge duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (le, type, instance))",
       "leglightlikeFormat": "{{instance}} {{type}}"
      }
     ]
    },
    {
     "title": "CausetStorage async write duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_bucket{instance=~\"$instance\", type=\"write\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_bucket{instance=~\"$instance\", type=\"write\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "rate(einsteindb_causetStorage_engine_async_request_duration_seconds_sum{instance=~\"$instance\", type=\"write\"}[1m]) / rate(einsteindb_causetStorage_engine_async_request_duration_seconds_count{instance=~\"$instance\", type=\"write\"}[1m])",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "Prewrite latch wait duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_bucket{instance=~\"$instance\", type=\"prewrite\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_bucket{instance=~\"$instance\", type=\"prewrite\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_sum{instance=~\"$instance\", type=\"prewrite\"}[1m]) / rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_count{instance=~\"$instance\", type=\"prewrite\"}[1m])",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "Commit latch wait duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_bucket{instance=~\"$instance\", type=\"commit\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_bucket{instance=~\"$instance\", type=\"commit\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_sum{instance=~\"$instance\", type=\"commit\"}[1m]) / rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_count{instance=~\"$instance\", type=\"commit\"}[1m])",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "Applightlike log duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_sum{instance=~\"$instance\"}[1m]) / rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_count{instance=~\"$instance\"}[1m])",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "Applightlike log duration per server",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      }
     ]
    },
    {
     "title": "Commit log duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_sum{instance=~\"$instance\"}[1m])) / sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_count{instance=~\"$instance\"}[1m]))",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Commit log duration per server",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_commit_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      }
     ]
    },
    {
     "title": "Apply log duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_apply_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_apply_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "rate(einsteindb_violetabftstore_apply_log_duration_seconds_sum{instance=~\"$instance\"}[1m]) / rate(einsteindb_violetabftstore_apply_log_duration_seconds_count{instance=~\"$instance\"}[1m])",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "Apply log duration per server",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_apply_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      }
     ]
    },
    {
     "title": "Propose wait duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "rate(einsteindb_violetabftstore_request_wait_time_duration_secs_sum{instance=~\"$instance\"}[1m]) / rate(einsteindb_violetabftstore_request_wait_time_duration_secs_count{instance=~\"$instance\"}[1m])",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "Apply wait duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_apply_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_apply_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "rate(einsteindb_violetabftstore_apply_wait_time_duration_secs_sum{instance=~\"$instance\"}[1m]) / rate(einsteindb_violetabftstore_apply_wait_time_duration_secs_count{instance=~\"$instance\"}[1m]) ",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "KV Lmdb write duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_max\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} max"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_percentile99\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_percentile95\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_average\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "VioletaBft Lmdb write duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_max\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} max"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_percentile99\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_percentile95\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "avg(einsteindb_engine_write_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"write_average\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "VioletaBft Lmdb WAL sync operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(einsteindb_engine_wal_file_synced{instance=~\"$instance\", db=\"violetabft\"}[1m])",
       "leglightlikeFormat": "{{instance}} sync"
      }
     ]
    },
    {
     "title": "VioletaBft Lmdb WAL sync duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "einsteindb_engine_wal_file_sync_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"wal_file_sync_max\"}",
       "leglightlikeFormat": "{{instance}} max"
      },
      {
       "expr": "einsteindb_engine_wal_file_sync_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"wal_file_sync_percentile99\"}",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "einsteindb_engine_wal_file_sync_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"wal_file_sync_percentile95\"}",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "einsteindb_engine_wal_file_sync_micro_seconds{instance=~\"$instance\", db=\"violetabft\",type=\"wal_file_sync_average\"}",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    },
    {
     "title": "Lmdb write stall duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_max\"}) by (db)",
       "leglightlikeFormat": "{{db}} max"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile99\"}) by (db)",
       "leglightlikeFormat": "{{db}} 99%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile95\"}) by (db)",
       "leglightlikeFormat": "{{db}} 95%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_average\"}) by (db)",
       "leglightlikeFormat": "{{db}} avg"
      }
     ]
    },
    {
     "title": "IO utilization",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[1m]) > 0",
       "leglightlikeFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total[5m]) + rate(node_disk_writes_completed_total[5m])",
       "leglightlikeFormat": "{{instance}} IOPs"
      }
     ]
    },
    {
     "title": "Disk Write Latency (ms)",
     "type": "graph",
     "description": "DISK seconds Read/ Write Latency.\n- Critical:\n  - Recommlightlikeed performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total[5m])/ rate(node_disk_writes_completed_total[5m])) > 0",
       "leglightlikeFormat": "{{instance}}: [{{ device }}]"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[5m]) + irate(node_disk_written_bytes_total[5m]) > 0",
       "leglightlikeFormat": "{{instance}}: [{{ device }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Stall - $db",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "db",
   "collapsed": true,
   "panels": [
    {
     "title": "Level0 SST file number",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_num_files_at_level{instance=~\"$instance\", db=\"kv\", level=\"0\"}) by (instance, causet)",
       "leglightlikeFormat": "{{instance}} {{causet}}"
      }
     ]
    },
    {
     "title": "ImmuBlock mem-Block number",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_num_immuBlock_mem_Block{instance=~\"$instance\", db=\"$db\"}) by (instance, causet)",
       "leglightlikeFormat": "{{instance}} {{causet}}"
      }
     ]
    },
    {
     "title": "Plightlikeing compaction bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_plightlikeing_compaction_bytes{instance=~\"$instance\", db=\"$db\"}) by (instance, causet)",
       "leglightlikeFormat": "{{instance}} {{causet}}"
      }
     ]
    },
    {
     "title": "Lmdb write stall duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_max\", db=\"$db\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} max"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile99\", db=\"$db\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} 99%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile95\", db=\"$db\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} 95%"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_average\", db=\"$db\"}) by (instance)",
       "leglightlikeFormat": "{{instance}} avg"
      }
     ]
    }
   ]
  },
  {
   "title": "OOM",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block cache size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(einsteindb_engine_block_cache_size_bytes{instance=~\"$instance\", db=\"kv\"}) by(causet)",
       "leglightlikeFormat": "{{causet}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes{instance=~\"$instance\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Huge Brane",
   "type": "EventIdx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Approximate Brane size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_brane_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_brane_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_violetabftstore_brane_size_sum{instance=~\"$instance\"}[1m])) / sum(rate(einsteindb_violetabftstore_brane_size_count{instance=~\"$instance\"}[1m])) ",
       "leglightlikeFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.999999, sum(rate(einsteindb_violetabftstore_brane_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "99.9999%"
      }
     ]
    },
    {
     "title": "Split checker CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"split_check\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}