{
 "title": "Test-Cluster-Performance-Write",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MilevaDB-Server",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "MilevaDB query durations by histogram buckets with different percents",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "80"
      }
     ]
    },
    {
     "title": "99% Get Token Duration",
     "type": "graph",
     "description": "Duration (us) for getting token, it should be small until concurrency limit is reached.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_get_token_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "99"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "MilevaDB current connection counts",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "milevadb_server_connections", "leglightlikeFormat": "{{instance}}" },
      {
       "expr": "sum(milevadb_server_connections)",
       "leglightlikeFormat": "total"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "description": "MilevaDB heap memory size in use ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"milevadb.*\"}",
       "leglightlikeFormat": "{{instance}}-{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parse",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Parse Duration",
     "type": "graph",
     "description": "The time cost of parsing SQL to AST",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_parse_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compile",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Compile Duration",
     "type": "graph",
     "description": "The time cost of building the query plan",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_compile_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "Bucketed histogram of transaction execution durations, including retry",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "95-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Statement Num",
     "type": "graph",
     "description": "MilevaDB statements numbers within one transaction. Internal means MilevaDB inner transaction",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
       "leglightlikeFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
       "leglightlikeFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Retry Num",
     "type": "graph",
     "description": "MilevaDB transaction retry histogram bucket statistics",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(milevadb_session_retry_num_bucket[30s])) by (le))",
       "leglightlikeFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_retry_num_bucket[30s])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_session_retry_num_bucket[30s])) by (le))",
       "leglightlikeFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "KV",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Cmd Duration 999",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket{type=~\"commit\"}[1m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Duration 99",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket{type=~\"commit\"}[1m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Dagger Resolve OPS",
     "type": "graph",
     "description": "dagger resolve times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_lock_resolver_actions_total[1m])) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% KV Backoff Duration",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_backoff_seconds_bucket[5m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Backoff OPS",
     "type": "graph",
     "description": "kv causetStorage backoff times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_backoff_seconds_count[1m])) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FIDel Client",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIDel TSO Wait Duration",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(fidel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(fidel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(fidel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "90"
      }
     ]
    },
    {
     "title": "FIDel TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client slightlikeing TSO request until received the response.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(fidel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(fidel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(fidel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% gRPC messge duration",
     "type": "graph",
     "description": "The execution time of gRPC message",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_grpc_msg_duration_seconds_bucket{type=~\"kv_prewrite|kv_commit\"}[5m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gRPC poll CPU",
     "type": "graph",
     "description": "The CPU utilization of gRPC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"grpc.*\"}[1m])) by (instance, name))",
       "leglightlikeFormat": "{{ instance }} - {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interlock_Semaphore",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interlock_Semaphore latch wait duration",
     "type": "graph",
     "description": "the time which is caused by latch wait ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_bucket[5m])) by (le, type))",
       "leglightlikeFormat": "99% - {{ type }}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_bucket[5m])) by (le, type))",
       "leglightlikeFormat": "95% - {{ type }}"
      },
      {
       "expr": "rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_sum[5m]) / rate(einsteindb_interlock_semaphore_latch_wait_duration_seconds_count[5m])",
       "leglightlikeFormat": "avg - {{ type }}"
      }
     ]
    },
    {
     "title": "Interlock_Semaphore worker CPU",
     "type": "graph",
     "description": "The CPU utilization of interlock_semaphore worker",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"sched_.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99% interlock_semaphore command duration",
     "type": "graph",
     "description": "The time consumed when executing commit command",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_semaphore_command_duration_seconds_bucket[1m])) by (le, type))",
       "leglightlikeFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "violetabftstore",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% propose wait duration by instance",
     "type": "graph",
     "description": "The wait time of each proposal",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_request_wait_time_duration_secs_bucket[1m])) by (le, instance))",
       "leglightlikeFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "VioletaBft store CPU",
     "type": "graph",
     "description": "The CPU utilization of violetabftstore thread",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"violetabftstore_.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CausetStorage async write duration",
     "type": "graph",
     "description": "The time consumed by processing asynchronous write requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_bucket{type=\"write\"}[5m])) by (le))",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_bucket{type=\"write\"}[5m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_sum{type=\"write\"}[5m])) / sum(rate(einsteindb_causetStorage_engine_async_request_duration_seconds_count{type=\"write\"}[5m]))",
       "leglightlikeFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Lmdb-VioletaBft",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% applightlike log duration by instance",
     "type": "graph",
     "description": "The time consumed when VioletaBft applightlikes log on each EinsteinDB instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_applightlike_log_duration_seconds_bucket[1m])) by (le, instance))",
       "leglightlikeFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Write duration",
     "type": "graph",
     "description": "The time consumed when executing write operation",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"violetabft\", type=\"write_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"violetabft\", type=\"write_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"violetabft\", type=\"write_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"violetabft\", type=\"write_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Lmdb-KV",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% apply wait duration by instance",
     "type": "graph",
     "description": "The time consumed when apply log requests are wait for being handled",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_apply_wait_time_duration_secs_bucket[5m])) by (le, instance))",
       "leglightlikeFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Apply log duration",
     "type": "graph",
     "description": "The time consumed when VioletaBft applies log",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_apply_log_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": " 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_apply_log_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_violetabftstore_apply_log_duration_seconds_sum[1m])) / sum(rate(einsteindb_violetabftstore_apply_log_duration_seconds_count[1m])) ",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Write duration",
     "type": "graph",
     "description": "The time consumed when executing write operation",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"kv\", type=\"write_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"kv\", type=\"write_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"kv\", type=\"write_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "max(einsteindb_engine_write_micro_seconds{db=\"kv\", type=\"write_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Async apply CPU",
     "type": "graph",
     "description": "The CPU utilization of async apply",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"apply_[0-9]+\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded causetStorage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal causetStorage problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_write_time_seconds_total[5m]) / irate(node_disk_writes_completed_total[5m])",
       "leglightlikeFormat": "Write: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_writes_completed_total[5m])",
       "leglightlikeFormat": "Write: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Bandwidth",
     "type": "graph",
     "description": "Shows volume of reads and writes the causetStorage is handling. This can be better measure of IO capacity usage for network attached and SSD causetStorage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash causetStorage life time.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_written_bytes_total[5m])",
       "leglightlikeFormat": "Write: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual causetStorage utilization. Different causetStorage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_write_time_seconds_total[5m])",
       "leglightlikeFormat": "Write: {{instance}} - {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}