{
 "title": "Test-Cluster-Performance-Read",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MilevaDB-Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "MilevaDB query durations by histogram buckets with different percents",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_server_handle_query_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "80"
      }
     ]
    },
    {
     "title": "99% Get Token Duration",
     "type": "graph",
     "description": "Duration (us) for getting token, it should be small until concurrency limit is reached.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_get_token_duration_seconds_bucket[1m])) by (le))",
       "leglightlikeFormat": "99"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "MilevaDB current connection counts",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "milevadb_server_connections", "leglightlikeFormat": "{{instance}}" },
      {
       "expr": "sum(milevadb_server_connections)",
       "leglightlikeFormat": "total"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "description": "MilevaDB heap memory size in use ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"milevadb.*\"}",
       "leglightlikeFormat": "{{instance}}-{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Parse Duration",
     "type": "graph",
     "description": "The time cost of parsing SQL to AST",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_parse_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Compile Duration",
     "type": "graph",
     "description": "The time cost of building the query plan",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_compile_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "Bucketed histogram of transaction execution durations, including retry",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "95-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_session_transaction_duration_seconds_bucket[1m])) by (le, sql_type))",
       "leglightlikeFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Statement Num",
     "type": "graph",
     "description": "MilevaDB statements numbers within one transaction. Internal means MilevaDB inner transaction",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
       "leglightlikeFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_session_transaction_statement_num_bucket[30s])) by (le, sql_type))",
       "leglightlikeFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Retry Num",
     "type": "graph",
     "description": "MilevaDB transaction retry histogram bucket statistics",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(milevadb_session_retry_num_bucket[30s])) by (le))",
       "leglightlikeFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_session_retry_num_bucket[30s])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(milevadb_session_retry_num_bucket[30s])) by (le))",
       "leglightlikeFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "KV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Cmd Duration 9999",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket{type=~\"get|batch_get|seek|seek_reverse\"}[1m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Duration 99",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_bucket{type=~\"get|batch_get|seek|seek_reverse\"}[1m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Lock Resolve OPS",
     "type": "graph",
     "description": "lock resolve times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_lock_resolver_actions_total[1m])) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% KV Backoff Duration",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_backoff_seconds_bucket[5m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Backoff OPS",
     "type": "graph",
     "description": "kv persistence backoff times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_backoff_seconds_count[1m])) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FIDel Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIDel TSO Wait Duration",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(fidel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(fidel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(fidel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "90"
      }
     ]
    },
    {
     "title": "FIDel TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client slightlikeing TSO request until received the response.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(fidel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(fidel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(fidel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "leglightlikeFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% gRPC messge duration",
     "type": "graph",
     "description": "The execution time of gRPC message",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_grpc_msg_duration_seconds_bucket{type=~\"kv_get|kv_batch_get|interlock\"}[5m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gRPC poll CPU",
     "type": "graph",
     "description": "The CPU utilization of gRPC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"grpc.*\"}[1m])) by (instance, name)",
       "leglightlikeFormat": "{{ instance }} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CausetStorage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CausetStorage ReadPool CPU",
     "type": "graph",
     "description": "The CPU utilization of readpool",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"store_read.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interlock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wait duration",
     "type": "graph",
     "description": "The time consumed when interlock requests are wait for being handled",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(einsteindb_interlock_request_wait_seconds_bucket[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_request_wait_seconds_bucket[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-99%"
      }
     ]
    },
    {
     "title": "Handle duration",
     "type": "graph",
     "description": "The time consumed when handling interlock requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(einsteindb_interlock_request_handle_seconds_bucket[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_interlock_request_handle_seconds_bucket[1m])) by (le,req))",
       "leglightlikeFormat": "{{req}}-99%"
      }
     ]
    },
    {
     "title": "Interlock CPU",
     "type": "graph",
     "description": "The CPU utilization of interlock",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{name=~\"cop_.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lmdb-KV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get duration",
     "type": "graph",
     "description": "The time consumed when executing get operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(einsteindb_engine_get_micro_seconds{db=\"kv\",type=\"get_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "max(einsteindb_engine_get_micro_seconds{db=\"kv\",type=\"get_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "max(einsteindb_engine_get_micro_seconds{db=\"kv\",type=\"get_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "max(einsteindb_engine_get_micro_seconds{db=\"kv\",type=\"get_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Get operations",
     "type": "graph",
     "description": "The count of get operations",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_engine_memtable_efficiency{db=\"kv\", type=\"memtable_hit\"}[1m]))",
       "leglightlikeFormat": "memtable"
      },
      {
       "expr": "sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=~\"block_cache_data_hit|block_cache_filter_hit\"}[1m]))",
       "leglightlikeFormat": "block_cache"
      },
      {
       "expr": "sum(rate(einsteindb_engine_get_served{db=\"kv\", type=\"get_hit_l0\"}[1m]))",
       "leglightlikeFormat": "l0"
      },
      {
       "expr": "sum(rate(einsteindb_engine_get_served{db=\"kv\", type=\"get_hit_l1\"}[1m]))",
       "leglightlikeFormat": "l1"
      },
      {
       "expr": "sum(rate(einsteindb_engine_get_served{db=\"kv\", type=\"get_hit_l2_and_up\"}[1m]))",
       "leglightlikeFormat": "l2_and_up"
      }
     ]
    },
    {
     "title": "Seek duration",
     "type": "graph",
     "description": "The time consumed when executing seek operation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(einsteindb_engine_seek_micro_seconds{db=\"kv\",type=\"seek_max\"})",
       "leglightlikeFormat": "max"
      },
      {
       "expr": "max(einsteindb_engine_seek_micro_seconds{db=\"kv\",type=\"seek_percentile99\"})",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "max(einsteindb_engine_seek_micro_seconds{db=\"kv\",type=\"seek_percentile95\"})",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "max(einsteindb_engine_seek_micro_seconds{db=\"kv\",type=\"seek_average\"})",
       "leglightlikeFormat": "avg"
      }
     ]
    },
    {
     "title": "Seek operations",
     "type": "graph",
     "description": "The count of seek operations",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_engine_locate{db=\"kv\", type=\"number_db_seek\"}[1m]))",
       "leglightlikeFormat": "seek"
      },
      {
       "expr": "sum(rate(einsteindb_engine_locate{db=\"kv\", type=\"number_db_seek_found\"}[1m]))",
       "leglightlikeFormat": "seek_found"
      },
      {
       "expr": "sum(rate(einsteindb_engine_locate{db=\"kv\", type=\"number_db_next\"}[1m]))",
       "leglightlikeFormat": "next"
      },
      {
       "expr": "sum(rate(einsteindb_engine_locate{db=\"kv\", type=\"number_db_next_found\"}[1m]))",
       "leglightlikeFormat": "next_found"
      },
      {
       "expr": "sum(rate(einsteindb_engine_locate{db=\"kv\", type=\"number_db_prev\"}[1m]))",
       "leglightlikeFormat": "prev"
      },
      {
       "expr": "sum(rate(einsteindb_engine_locate{db=\"kv\", type=\"number_db_prev_found\"}[1m]))",
       "leglightlikeFormat": "prev_found"
      }
     ]
    },
    {
     "title": "Block cache hit",
     "type": "graph",
     "description": "The hit rate of block cache",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_engine_cache_efficiency{instance=~\"$instance\", db=\"$db\", type=\"block_cache_hit\"}[1m])) / (sum(rate(einsteindb_engine_cache_efficiency{db=\"$db\", type=\"block_cache_hit\"}[1m])) + sum(rate(einsteindb_engine_cache_efficiency{db=\"$db\", type=\"block_cache_miss\"}[1m])))",
       "leglightlikeFormat": "all"
      },
      {
       "expr": "sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_data_hit\"}[1m])) / (sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_data_hit\"}[1m])) + sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_data_miss\"}[1m])))",
       "leglightlikeFormat": "data"
      },
      {
       "expr": "sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_filter_hit\"}[1m])) / (sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_filter_hit\"}[1m])) + sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_filter_miss\"}[1m])))",
       "leglightlikeFormat": "filter"
      },
      {
       "expr": "sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_index_hit\"}[1m])) / (sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_index_hit\"}[1m])) + sum(rate(einsteindb_engine_cache_efficiency{db=\"kv\", type=\"block_cache_index_miss\"}[1m])))",
       "leglightlikeFormat": "index"
      },
      {
       "expr": "sum(rate(einsteindb_engine_bloom_efficiency{db=\"kv\", type=\"bloom_prefix_useful\"}[1m])) / sum(rate(einsteindb_engine_bloom_efficiency{db=\"kv\", type=\"bloom_prefix_checked\"}[1m]))",
       "leglightlikeFormat": "bloom prefix"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded persistence indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal persistence problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_read_time_seconds_total[5m]) / irate(node_disk_reads_completed_total[5m])",
       "leglightlikeFormat": "Read: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_reads_completed_total[5m])",
       "leglightlikeFormat": "Read: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Bandwidth",
     "type": "graph",
     "description": "Shows volume of reads and writes the persistence is handling. This can be better measure of IO capacity usage for network attached and SSD persistence as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash persistence life time.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_read_bytes_total[5m])",
       "leglightlikeFormat": "Read: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual persistence utilization. Different persistence types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_read_time_seconds_total[5m])",
       "leglightlikeFormat": "Read: {{instance}} - {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}