{
 "title": "Test-Cluster-EinsteinDB-Summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "db",
    "query": "label_values(einsteindb_engine_block_cache_size_bytes, db)"
   },
   {
    "name": "command",
    "label": "command",
    "query": "label_values(einsteindb_causetStorage_command_total, type)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(einsteindb_engine_size_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CausetStore size",
     "type": "graph",
     "description": "The causetStorage size per EinsteinDB instance",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_engine_size_bytes{instance=~\"$instance\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available size",
     "type": "graph",
     "description": "The available capacity size of each EinsteinDB instance",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_store_size_bytes{instance=~\"$instance\", type=\"available\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Capacity size",
     "type": "graph",
     "description": "The capacity size per EinsteinDB instance",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_store_size_bytes{instance=~\"$instance\", type=\"capacity\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "description": " \tThe CPU usage of each EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": " \tThe memory usage of each EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(process_resident_memory_bytes{instance=~\"$instance\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IO utilization",
     "type": "graph",
     "description": " \tThe I/O utilization per EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[1m])",
       "leglightlikeFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "MBps",
     "type": "graph",
     "description": "The total bytes of read and write in each EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"wal_file_bytes\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}-write"
      },
      {
       "expr": "sum(rate(einsteindb_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=~\"bytes_read|iter_bytes_read\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}-read"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "The QPS of different kinds of commands in each EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_duration_seconds_count{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (instance,type)",
       "leglightlikeFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "Errps",
     "type": "graph",
     "description": "The total number of the gRPC message failures",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_fail_total{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}-grpc-msg-fail"
      },
      {
       "expr": "sum(delta(einsteindb_fidel_heartbeat_message_total{instance=~\"$instance\", type=\"noop\"}[1m])) by (instance) < 1",
       "leglightlikeFormat": "{{instance}}-fidel-heartbeat"
      },
      {
       "expr": "sum(rate(einsteindb_critical_error_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Leader",
     "type": "graph",
     "description": "The number of leaders per EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_violetabftstore_brane_count{instance=~\"$instance\", type=\"leader\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Brane",
     "type": "graph",
     "description": " \tThe number of Branes on each EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_violetabftstore_brane_count{instance=~\"$instance\", type=\"brane\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_critical_error_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Server is busy",
     "type": "graph",
     "description": "It contains some kinds of events such as write stall, channel full, interlock_semaphore busy, and interlock full, which will make the EinsteinDB instance unavailable temporarily.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_interlock_semaphore_too_busy_total{instance=~\"$instance\"}[1m])) by (instance)",
       "leglightlikeFormat": "interlock_semaphore-{{instance}}"
      },
      {
       "expr": "sum(rate(einsteindb_channel_full_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "channelfull-{{instance}}-{{type}}"
      },
      {
       "expr": "sum(rate(einsteindb_interlock_request_error{instance=~\"$instance\", type='full'}[1m])) by (instance)",
       "leglightlikeFormat": "interlock-{{instance}}"
      },
      {
       "expr": "avg(einsteindb_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile99\"}) by (instance)",
       "leglightlikeFormat": "stall-{{instance}}"
      }
     ]
    },
    {
     "title": "Server report failures",
     "type": "graph",
     "description": "The total number of reporting failure messages",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_server_report_failure_msg_total{instance=~\"$instance\"}[1m])) by (type,instance,store_id)",
       "leglightlikeFormat": "{{instance}} - {{type}} - to - {{store_id}}"
      }
     ]
    },
    {
     "title": "VioletaBftstore error",
     "type": "graph",
     "description": "The number of VioletaBftstore errors per type on each EinsteinDB instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_causetStorage_engine_async_request_total{instance=~\"$instance\", status!~\"success|all\"}[1m])) by (instance, status)",
       "leglightlikeFormat": "{{instance}}-{{status}}"
      }
     ]
    },
    {
     "title": "Interlock_Semaphore error",
     "type": "graph",
     "description": "The number of different interlock_semaphore errors on each EinsteinDB instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_interlock_semaphore_stage_total{instance=~\"$instance\", stage=~\"snapshot_err|prepare_write_err\"}[1m])) by (instance, stage)",
       "leglightlikeFormat": "{{instance}}-{{stage}}"
      }
     ]
    },
    {
     "title": "Interlock error",
     "type": "graph",
     "description": "The number of different interlock errors on each EinsteinDB instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_interlock_request_error{instance=~\"$instance\"}[1m])) by (instance, reason)",
       "leglightlikeFormat": "{{instance}}-{{reason}}"
      }
     ]
    },
    {
     "title": "gRPC message error",
     "type": "graph",
     "description": "The number of different gRPC message errors on each EinsteinDB instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_fail_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Leader drop",
     "type": "graph",
     "description": "The count of dropped leader in each EinsteinDB instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(einsteindb_violetabftstore_brane_count{instance=~\"$instance\", type=\"leader\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Leader missing",
     "type": "graph",
     "description": "The count of missing leaders per EinsteinDB instance",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_violetabftstore_leader_missing{instance=~\"$instance\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CAUSET size",
     "type": "graph",
     "description": " \tThe total size of each PrimaryCauset family",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_engine_size_bytes{instance=~\"$instance\"}) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "CausetStore size",
     "type": "graph",
     "description": "The causetStorage size per EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(einsteindb_engine_size_bytes{instance=~\"$instance\"}) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Channel full",
     "type": "graph",
     "description": "The total number of channel full errors on each EinsteinDB instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_channel_full_total{instance=~\"$instance\"}[1m])) by (instance, type)",
       "leglightlikeFormat": "{{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "Approximate Brane size",
     "type": "graph",
     "description": "The approximate Brane size",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_violetabftstore_brane_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(einsteindb_violetabftstore_brane_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "leglightlikeFormat": "95%"
      },
      {
       "expr": "sum(rate(einsteindb_violetabftstore_brane_size_sum{instance=~\"$instance\"}[1m])) / sum(rate(einsteindb_violetabftstore_brane_size_count{instance=~\"$instance\"}[1m])) ",
       "leglightlikeFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "gRPC message count",
     "type": "graph",
     "description": "The count of different kinds of gRPC message",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_duration_seconds_count{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gRPC message failed",
     "type": "graph",
     "description": "The count of different kinds of gRPC message which is failed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_fail_total{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% gRPC messge duration",
     "type": "graph",
     "description": "The gRPC message duration per message type (P99)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(einsteindb_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type!=\"kv_gc\"}[1m])) by (le, type))",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Average gRPC messge duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_grpc_msg_duration_seconds_sum{instance=~\"$instance\"}[1m])) by (type) / sum(rate(einsteindb_grpc_msg_duration_seconds_count[1m])) by (type)",
       "leglightlikeFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread CPU",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "VioletaBft store CPU",
     "type": "graph",
     "description": "The CPU utilization of violetabftstore thread",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"violetabftstore_.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Async apply CPU",
     "type": "graph",
     "description": "The CPU utilization of async apply",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"apply_[0-9]+\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interlock_Semaphore worker CPU",
     "type": "graph",
     "description": "The CPU utilization of interlock_semaphore worker",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"sched_.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gRPC poll CPU",
     "type": "graph",
     "description": "The CPU utilization of gRPC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"grpc.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Interlock CPU",
     "type": "graph",
     "description": "The CPU utilization of interlock",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_normal.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - normal"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_high.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - high"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"cop_low.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - low"
      }
     ]
    },
    {
     "title": "CausetStorage ReadPool CPU",
     "type": "graph",
     "description": "The CPU utilization of readpool",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_norm.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - normal"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_high.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - high"
      },
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"store_read_low.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}} - low"
      }
     ]
    },
    {
     "title": "Split check CPU",
     "type": "graph",
     "description": " \tThe CPU utilization of split check",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"split_check\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Lmdb CPU",
     "type": "graph",
     "description": "The CPU utilization of Lmdb",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"lmdb.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC worker CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"gc_worker.*\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Snapshot worker CPU",
     "type": "graph",
     "description": "The CPU utilization of snapshot worker",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"snapshot_worker\"}[1m])) by (instance)",
       "leglightlikeFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FIDel",
   "type": "Evcausetidx",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIDel requests",
     "type": "graph",
     "description": " \tThe count of requests that EinsteinDB lightlikes to FIDel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_fidel_request_duration_seconds_count{instance=~\"$instance\"}[1m])) by (type)",
       "leglightlikeFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "FIDel request duration (average)",
     "type": "graph",
     "description": "The time consumed by requests that EinsteinDB lightlikes to FIDel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_fidel_request_duration_seconds_sum{instance=~\"$instance\"}[1m])) by (type) / sum(rate(einsteindb_fidel_request_duration_seconds_count{instance=~\"$instance\"}[1m])) by (type)",
       "leglightlikeFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "FIDel heartbeats",
     "type": "graph",
     "description": "The total number of FIDel heartbeat messages",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_fidel_heartbeat_message_total{instance=~\"$instance\"}[1m])) by (type)",
       "leglightlikeFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "FIDel validate peers",
     "type": "graph",
     "description": "The total number of peers validated by the FIDel worker",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(einsteindb_fidel_validate_peer_total{instance=~\"$instance\"}[1m])) by (type)",
       "leglightlikeFormat": "{{ type }}"
      }
     ]
    }
   ]
  }
 ]
}